### ISSUE TITLE
Connection requests from previous login appears on current login

### ISSUE THREAD

**Issue by Wipeless** [ImpowerGames/impower#65]
**Describe the bug**
Connection requests from a previous user's login appears on the new user's Connection request page.

**To Reproduce**
1. Login as user A.
2. Request to make a Connection with user B.
3. Logout from User A
4. Login as user B.
5. View the Connections page 
6. Verify that the request from user A is visible.
7. Logout from User B
8. Login as user C.
9. View the Connections page.

**Expected Result**
The request between user A and user B appears for the new user that's logged in user C.  This connection request page appears to be cached.

**Actual Result**
The new user C cannot see the requests of user A and user B.

**Screenshots**
![contactRequest1](https://user-images.githubusercontent.com/1523864/140674905-caf85a6c-fcea-420f-9770-641a114c3637.png)

![contactRequest2](https://user-images.githubusercontent.com/1523864/140674911-e39aa705-f2ea-41d0-92db-55c82807b79b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 95.0.4638.69 

**Additional context**
Refreshing the page will clear the cached request.

**Comment by lovelle-cardoso** [comment]
@Wipeless Good catch! Seems like Realtime Database always pulls from cache first when observing data and there's unfortunately no way to clear out the cache when a user logs out. So I changed the initial RTDB fetches that happen when a user logs in to be one-time gets instead of an observe calls.

https://stackoverflow.com/questions/24416541/firebase-persistence-clear-firebase-cache

**Comment by Wipeless** [comment]
Fixed!
